# Generated by Django 6.0.1 on 2026-01-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='description',
        ),
        migrations.RemoveField(
            model_name='hero',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sociallink',
            name='icon',
        ),
        migrations.AddField(
            model_name='hero',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
