# Generated by Django 6.0.1 on 2026-01-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_hero_description_remove_hero_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='core/'),
        ),
    ]
