# Generated by Django 6.0.1 on 2026-01-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_about_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.CharField(blank=True, help_text='Static path: e.g., images/about/me.jpg', max_length=200, null=True),
        ),
    ]
