# Generated by Django 6.0.1 on 2026-01-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_about_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon',
            field=models.TextField(blank=True, help_text='Enter HTML or SVG for the icon', null=True),
        ),
    ]
