# Generated by Django 6.0.1 on 2026-01-12 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sociallink_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('tech_stack', models.CharField(help_text='Comma-separated values e.g. Django, PostgreSQL, JavaFX', max_length=300)),
                ('features', models.TextField(blank=True, help_text='One feature per line')),
                ('live_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['year']},
        ),
        migrations.AddField(
            model_name='hero',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hero',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(help_text='Percentage (0–100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.TextField(blank=True, default='', help_text='Paste SVG or HTML icon code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
