# Generated by Django 6.0.1 on 2026-01-15 16:43

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='cv',
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='about_image'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='project_image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='skill_icon'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='proficiency',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='timeline_icon'),
        ),
    ]
